version: '3.5'  

services: 
    backend: 
      image: localhost/backend-example 
      build: . 
      # :Z is needed for podman-compose to work with SELinux see https://github.com/containers/podman-compose/issues/41
      volumes: 
        - ./logs.txt:/app/logs.txt:Z
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_HOST=db
      #ports: 
      #  - 8000:8000
      depends_on:
        - db
    redis:
      image: redis
    frontend: 
      image: localhost/frontend-example
      build: ../frontend-example-docker
      #ports: 
      #  - 5000:5000
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: example
      container_name: db_backend
      volumes:
        - database:/var/lib/postgresql/data
    reverse_proxy:
      image: nginx
      volumes:
        - ../nginx/nginx.conf:/etc/nginx/nginx.conf:Z
      ports: 
        - 80:80
        
volumes:
  database:
