version: '3.5'

services: 
    first_volume_exercise:  
      image: docker.io/devopsdockeruh/first_volume_exercise
      build: . 
      # :Z is needed for podman-compose to work with SELinux see https://github.com/containers/podman-compose/issues/41
      volumes: 
        - ./logs.txt:/usr/app/logs.txt:Z
      container_name: first_volume_exercise
