version: '3' 
services: 
    build_service:  
      image: mbuet2ner/build_service
      build: . 
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      container_name: build_service
