FROM ubuntu:16.04 

WORKDIR /app
COPY . . 
RUN apt-get update && apt-get install -y curl 
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs
RUN node -v && npm -v
RUN npm install
RUN npm audit fix
EXPOSE 8000
CMD npm start
