version: '3.5'

services:
  training:
    image: ml-kurkkumopo-training
    build: ./ml-kurkkumopo-training
    container_name: ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
  backend:
    image: ml-kurkkumopo-backend 
    build: ./ml-kurkkumopo-backend
    volumes:
      - model:/src/model
    depends_on:
      - training
    ports:
      - 5000:5000
  frontend:
    image: ml-kurkkumopo-frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000

volumes:
  model:
  imgs:
  data:
